### ISSUE TITLE
doc - usuarios piloto

### ISSUE THREAD

**Issue by GuilleX7** [ISPP-Eventia/eventus#119]
## descripcion
actualización del documento de usuarios pilotos incluyendo planes de gestión de usuarios pilotos para los siguientes sprints, así como la información que sea necesaria para terminar el documento de cara a la siguiente entrega

## to-do
- [x] explicar planes de gestión de usuarios pilotos para futuros sprints
- [x] adiciones que se consideren necesarias

**Comment by josaloroc** [comment]
-Se puede consultar la información relativa a esta tarea en el documento Plan de Pilotaje / Compromiso del P4.
-Dentro de P2 / Formularios, se puede ver los formularios creados para enviar a los usuarios piloto. El creado recientemente ha sido "EventUS, encuesta de satisfacción y feedback".
