### ISSUE TITLE
doc - prototipo actual (vídeo)

### ISSUE THREAD

**Issue by GuilleX7** [ISPP-Eventia/eventus#125]
## descripcion
Grabar un vídeo capturando la pantalla mostrando el prototipo actual. Se prefiere formato vídeo dado que el directo puede dar problemas. Dada la duración máxima de la presentación, 12 minutos, no creo que sea conveniente que el vídeo dure más de 45 segundos, por lo que probablemente haya que editarlo para recortar escenas y mostrar texto explicativo.

## to-do
- [x] realizar vídeo de prototipo actual

## recursos
- prototipo de la aplicación

**Comment by marpedrod3** [comment]
Se ha hecho el vídeo y se ha subido a Google Drive.
