### ISSUE TITLE
doc - resultados de las herramientas de automatización de la calidad del software

### ISSUE THREAD

**Issue by GuilleX7** [ISPP-Eventia/eventus#127]
## descripcion
Analizar y mostrar los resultados de todas las herramientas de automatización de la calidad del software, como Codacy, etc.

## to-do
- [x] analizar resultados de herramientas de calidad

## recursos
- resultados de herramientas de calidad

**Comment by josaloroc** [comment]
Se han establecido dos diapositivas a modo de base en la presentación. Se muestran los resultados del dashboard de codacy de forma general y se ha añadido una breve descripción en las anotaciones.

Se ha establecido esta plantilla para solo tener que cambiar los datos en las diapositivas que se actualicen en el dashboard de aquí al miércoles
