### ISSUE TITLE
doc - resumen del compromiso de usuarios piloto

### ISSUE THREAD

**Issue by GuilleX7** [ISPP-Eventia/eventus#132]
## descripcion
Crear un documento resumen del compromiso de los usuarios piloto, explicando qué acciones se comprometen a realizar y en qué periodo de tiempo.

## to-do
- [x] resumen del compromiso

## recursos
- archivos de google drive

**Comment by josaloroc** [comment]
-Issue derivada de #119 . Información en el documento correspondiente.
