### ISSUE TITLE
doc - plan de gestión de los usuarios piloto para el siguiente sprint

### ISSUE THREAD

**Issue by GuilleX7** [ISPP-Eventia/eventus#134]
## descripcion
Definir el plan de gestión de los usuarios piloto para el sprint siguiente, cómo recogeremos su feedback, etc.

## to-do
- [x] definir el plan

## recursos
- archivos de google drive

**Comment by josaloroc** [comment]
-Issue derivada de https://github.com/ISPP-Eventia/eventus/issues/119 . Información en el documento correspondiente.
