### ISSUE TITLE
Feed Back - QA

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#183]
## description
Recolección de mejoras a implementar sobre los casos de uso implementados.

> Se incluirán notas de usuario piloto y mejoras o errores detectados internemente

## bugs
- [x] cuando quieres retroceder a la página anterior, se queda en blanco y ni recargando la página vuelve a funcionar. Tengo que salir y volver a entrar
- [x] Al crear un nuevo evento no aparece en el listado de eventos disponibles (paginación)
- [x] método de pago inexistente

## improvements
- [x] Ul typography Size
- [x] Event List Segmentizada
    - [x] Ul
    - [x] endpoints
- [x] diferenciación de patrocinio en función de la cantidad aportada
- [ ] etiquetas para los eventos
- [ ] "premio" por ganar
- [ ] búsqueda / categorización de eventos

**Comment by marpedrod3** [comment]
Describir los mensajes de error de los formularios en español

**Comment by marpedrod3** [comment]
El 60% ha marcado con 5 puntos la facilidad de uso
El 30% ha marcado con 4 puntos la facilidad de uso
El 10% ha marcado con 3 puntos la facilidad de uso.
Nadie ha marcado el 1 o el 2

**Comment by marpedrod3** [comment]
Las funcionalidades que más han valorado:
-Participar eventos 
-Recibir dinero por organizar un evento
-Patrocinar eventos
-Descripción del evento
-Buscar alojamiento

**Comment by marpedrod3** [comment]
Anotación: Todo funciona bien pero cuando quieres retroceder a la página anterior, se queda en blanco y ni recargando la página vuelve a funcionar. Tengo que salir y volver a entrar

**Comment by marpedrod3** [comment]
Funcionalidades que no han funcionado como esperaban:
-Todo funciona bien pero cuando quieres retroceder a la página anterior, se queda en blanco y ni recargando la página vuelve a funcionar. Tengo que salir y volver a entrar
-Al crear un nuevo evento no aparece en el listado de eventos disponibles
-La aplication esta llena de errores.
-Ver información de quien crea el evento, creo que puede ser bueno tener un perfil de cada uno que cree con el fin de darle "cierta credibilidad"

**Comment by marpedrod3** [comment]
Qué echan en falta:
-Información sobre qué diferencias existen a la hora de patrocinar un evento con 1€ o con 1000€ (mayor o menor publicidad de la marca, mejor posicionamiento del logo de ls marca en el cartel del evento… etc.)
-Me gustaria que el proceso de encontrar eventos de mi interes sea mas facil

Muchos también han comentado que les ha parecido bastante bien y no echan en falta nada.

**Comment by marpedrod3** [comment]
Funcionalidades que les gustaría añadir:
-A la hora de unirte a un evento, dar la opción a un chat con el que poder comunicarte con el organizador y comentarle las dudas que puedas tener
-Organizar los eventos por tipo: música, teatro, cine, deporte… etc.
-Un buscador por fecha
-Un buscador por fecha
-Dividir por niveles los eventos, eventos con mucho mas premio para la gente que lleve mas tiempo participando.
-Alguna funcionalidad que permitiera ver si otros amigos tuyos o personas conocidas también atienden al mismo evento
-Que tuviera algún menú lateral para ver los eventos/creadores
-Si tuviera una función para difundir/compartir un evento específico (dentro de la misma) estaría bien. Aunque tampoco es imprescindible.
-Poder buscar de forma más sencilla los eventos.
-Dividir por niveles los eventos, eventos con mucho mas premio para la gente que lleve mas tiempo participando.

**Comment by marpedrod3** [comment]
En relación a la apariencia y el estilo, un 30% han marcado un 5, un 45% han marcado un 4 y un 25% han marcado un 3

**Comment by marpedrod3** [comment]
En relación a la facilidad de uso de la aplicación, un 45% ha marcado un 5, un 45% ha marcado un 4, un 5% ha marcado un 3 y un 5% ha marcado un 2

**Comment by marpedrod3** [comment]
Los comentarios sobre la primera impresión radican principalmente en lo intuitiva que es, aunque hay algún comentario sobre que es algo básico.

**Comment by marpedrod3** [comment]
En relación a lo que ha resultado confuso, muchos han señalado que nada, pero otros han indicado el método de pago, unos han indicado que el alojamiento parece que está buscando un hotel y otros han comentado que la apariencia la cambiarían.

**Comment by marpedrod3** [comment]
Hay comentarios bastante positivos respecto a la gestión sobre el plan de pruebas

**Comment by marpedrod3** [comment]
Algunas recomendaciones son las siguientes:
-La recomendación de ejemplo (grupo Telegram) es muy buena idea y creo que la más aficaz a parte del correo electronico
-Creo que la opción del correo electrónico es la mas correcta
-Creación de una lista de difusión por correo electrónico para notificar las diferentes fases de desarrollo y las novedades implementadas en la aplicación
-Alguna red social o contacto con alguna persona para aportar más confianza al interesado

**Comment by marpedrod3** [comment]
Comentarios y/o sugerencias:
-Colaborar a futuro con creadores de contenido, realizando eventos con ellos etc
-Copiar aplicationes similares o contratar a un UX :))
-Necesito más información
