### ISSUE TITLE
doc - key business idea v2

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#19]
## descripcion
aplicar feedback y expandir los campos solicitados

## to-do
- [x] business idea refinement
- [x] elevator pitch

## recursos
- [feedback](https://github.com/ISPP-Eventia/eventus/discussions/18)

**Comment by pabgonmon2** [comment]
[Aquí ](https://docs.google.com/document/d/1o4bDrw_1H357SyqiZb5Kk1KTSL2LJVL8OhpGQQ6I5ss/edit#) hay un documento que incluye el elevator pitch y la idea de negocio. Se agradecería alguna revisión y sugerencias.
