### ISSUE TITLE
doc - storyboard (inversores)

### ISSUE THREAD

**Issue by GuilleX7** [ISPP-Eventia/eventus#201]
## descripcion
Crear un storyboard en formato cómic que siga las líneas de diseño generales corporativas. Debe estar enfocado a inversores de la aplicación.

## to-do
- [x] crear el storyboard

## recursos
- [storyboardthat](https://www.storyboardthat.com/es)

**Comment by marpedrod3** [comment]
Se ha creado el storyboard de los inversores
