### ISSUE TITLE
doc - recogida de feedback de usuarios pilotos y análisis

### ISSUE THREAD

**Issue by GuilleX7** [ISPP-Eventia/eventus#208]
## descripcion
Crear, revisar y enviar encuestas a los usuarios pilotos junto al prototipo de la aplicación desplegado utilizando el correo pertinente para ello. Recoger los resultados, analizarlos y extraer conclusiones.

## to-do
- [x] enviar encuestas y prototipo a los usuarios pilotos
- [ ] recoger y analizar los resultados del feedback

## recursos
- archivos de google drive
- cuenta de correo corporativa: space.eventus@gmail.com / @LArubiamecaemal

**Comment by marpedrod3** [comment]
Se han mandado los correos a los usuarios pilotos

**Comment by marpedrod3** [comment]
Se ha vuelto a enviar los correos a los usuarios pilotos
