### ISSUE TITLE
doc - branding

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#29]
## descripcion
definir el branding de la aplicación 

## to-do
- [x] logo
- [x] esquema de colores
- [ ] diseño acorde de las diapositivas (colores y fuentes)
## recursos
- enlaces de documentos o archivos
- enlaces de recursos útiles

**Comment by marpedrod3** [comment]
Se ha subido el logo a Figma

**Comment by marpedrod3** [comment]
Se indican los colores:

Para el rosa: #FF31FF
Para el negro: #000000
Para el blanco: #FFFFFF

**Comment by JSnow11** [comment]
> Se indican los colores:
> 
> Para el rosa: #FF31FF Para el negro: #000000 Para el blanco: #FFFFFF

Se necesitan más colores, necesitamos un esquema de color para toda la aplicación no solo el logo.

**Comment by JSnow11** [comment]
> Se ha subido el logo a Figma

El logo debe ser con fondo transparente, preferiblemente svg

**Comment by marpedrod3** [comment]
> > Se ha subido el logo a Figma
> 
> El logo debe ser con fondo transparente, preferiblemente svg

Se ha subido el logo en fondo transparente en .svg

**Comment by marpedrod3** [comment]
Colores añadidos:
#B3D5F2
#83C6FF
#F57CC6
#2F70D5
#50B66B
#FEA446
#414040
