### ISSUE TITLE
doc - recogida de feedback de usuarios pilotos y análisis

### ISSUE THREAD

**Issue by GuilleX7** [ISPP-Eventia/eventus#307]

**Comment by Almafe2510** [comment]
## BUGS:
- [] El usuario sale dos veces al participar en un torneo donde no había nadie
- [] Al participar en un evento lleva a la pasarela de pago para añadir una tarjeta pero luego no  redirecciona al evento seleccionado sino que tengo que volver a buscarlo y participar de nuevo
- [] Al participar en un evento compré tres tickets sin querer
- []  La contraseña no tiene mínimo 
- [] Si pongo la fecha de hoy , me sale birthdate: y el error, debería no salir lo de birthdate . He puesto que nací ayer y me ha dejado, en una cosa que hay que poner dinero debería ser al menos +16 
- [] Cuando no estás logueado te sale tu perfil y el icono de logout.
- [] Cuando me registro en un evento , durante un tiempo me salta "ya estás registrado en este evento" pero no me he registrado todavía.
## IMPROVEMENTS:
- [] Cambiar el símbolo del dólar por el del euro
- [] Cambiar el botón de inicio de sesión a uno más intuitivo
- [] Búsqueda de eventos por cercanía
- [] Seleccionar número de tickets que quiero comprar
- [] Regalar tickets a otro usuario registrado
- [] El botón de 'Mostrar todos' (eventos) podría ser más vistoso

**Comment by marpedrod3** [comment]
-cuando buscas tienes que iniciar sesión pero al principio como que funciona 
-login está en inglés pero luego todo está en castellano
-Creo que en proporción está todo muy pequeño
-El login podría estar centrado, que se pierde mucha pantalla a la derecha
-los iconos inferiores en la página principal parece con los puntos suspensivos que te van a llevar a algún lado si haces click en ellos, pero no te llevan a ningún lado Es como que intuitivamente los vas a seleccionar. 
Se podría poner alguna frase encima como: con eventus puedes: y ya que aparezcan abajo o algo. 
Cuando le das a comenzar te lleva como a inciar pero luego te pide el inicio de sesión. 

El no tienes cuenta? Regístrate ya! Debe iniciar también con los signos de exclamación e interrogación. 

En la dirección aparece el código postal abajo sin híper vínculo, queda raro que aparezca reina mercedes y eso no. A lo mejor en la misma línea con hipervinculo queda mejor.
