### ISSUE TITLE
doc - usuarios piloto detallados

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#37]
## descripcion
lista concreta de usuarios piloto detallando la diversidad, plan de pilotaje y metodos de feedback

> necesitamos hosts de eventos con infraestructura

## to-do
- [x] lista
- [x] especificar la diversidad de usuarios
- [x] feedback 
    - [x] encuestas con resultados, incluir cuanto pagarian, si lo usarían, caso de uso con el que se identifican ...

## recursos
- enlaces de documentos o archivos
- enlaces de recursos útiles

**Comment by josaloroc** [comment]
Se ha realizado lo siguiente para satisfacer la tarea:

1. Se ha procesado la información relativa a los usuarios piloto gracias al formulario que han ido respondiendo.
2. Se ha trasladado la información a la sección correspondiente de las trasparencias.

Estas trasparencias contienen información sobre:
-Listado de usuario especificando el total asignados a cada rol que desempeñarían principalmente.
-Aclaración de los intereses primarios/secundarios y diversidad.
-Muestra de los resultados más importantes de la encuesta.
-Plan de pilotaje respecto a los usuarios: formularios, issues de github y manuales de usuario.
