### ISSUE TITLE
doc - riesgos

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#39]
## descripcion
describir los riesgos de innovación, colaboración y tecnologicos

## to-do
- [x] innovación
- [x] colaboración
- [x] tecnológicos

## recursos
- enlaces de documentos o archivos
- enlaces de recursos útiles

**Comment by Almafe2510** [comment]
Realizado análisis de innovación, colaboración y tecnológico en diapositiva nº 15

**Comment by JSnow11** [comment]
> Realizado análisis de innovación, colaboración y tecnológico en diapositiva nº 15

No estan en las slides nuevas

**Comment by Almafe2510** [comment]
Ya están en las slides nuevas
