### ISSUE TITLE
doc - fotos

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#40]
## descripcion
fotos coorporativas: definir postura, recolectar fotos y añadirlas 

## to-do
- [x] pose
- [ ] recolección
- [ ] añadir

## recursos
- enlaces de documentos o archivos
- enlaces de recursos útiles

**Comment by beabelalv** [comment]
Hay que tomar una foto estando de frente, con camisa blanca y fondo blanco

![ejemplo2](https://user-images.githubusercontent.com/52604150/155979867-328ff1e0-71a5-4ea3-acb0-311f74e0598c.jpg)
