### ISSUE TITLE
doc - presentar el workflow

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#42]
## descripcion
usar el workflow definido en el readme y presentarlo sintéticamente

## to-do
- [x] consultar el readme
- [x] elaborar slides

## recursos
- [readme](https://github.com/ISPP-Eventia/eventus)

**Comment by antsandur2** [comment]
Se ha creado la diapositiva mostrando el Workflow a partir de readme

**Comment by JSnow11** [comment]
## review
![image](https://user-images.githubusercontent.com/47798577/156426015-4c452449-fb63-4f3f-b827-fc576bb62787.png)

- creo que sería mejor de izquierda a derecha en 2 filas
- estaría bien poner imagenes debajo de los titulos (imagen relacionada, tecnología que se usa, un ejemplo o algo por el estilo)

**Comment by antsandur2** [comment]
Ya he dejado en dos filas de izquierda a derecha y he colocado imágenes pero no en todos los textos porque referente a Commiting y Releasing no sé exactamente que imagen puedo colocar.
