### ISSUE TITLE
doc - contribución a la base de conocimiento

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#50]
## descripcion
contribuir de forma clara a la base de conocimiento

## to-do
- [x] añadir contribuciones
- [x] documentar la contribución #49 

## recursos
- [base de conocimiento compartido](https://www.notion.so/invite/92265daa92e62f27785689d2963940267cbc9a3b)

**Comment by antsandur2** [comment]
Se ha añadido a la base de conocimiento compartida las notas de las tres sesiones de clase.
Hemos indicado el número de nuestro grupo para que se vea nuestra contribución a la base de conocimiento.
Tenemos documentada las notas en el fichero Gestión del conocimiento en Drive.
