### ISSUE TITLE
doc - base de conocimiento

### ISSUE THREAD

**Issue by JSnow11** [ISPP-Eventia/eventus#95]
## descripcion
colaboración en la base del conocimiento y documentación de lo aportado y del proceso y metodologia de aportación

## to-do
- [x] coordinar con otros grupos
- [x] realizar aportaciones 
- [x] documentar

## recursos
- Google sites en la carpeta de Drive

**Comment by antsandur2** [comment]
Se ha realizado la coordinación con los grupos y somos responsables de subir todo el feedback recogido en las sesiones presenciales y completar el apartado de Competidores.

Se ha subido todo el feedback  y la información de competidores al Site.

Se ha documentado la aportación en el archivo de Drive [Base del conocimiento](https://docs.google.com/document/d/17m1uCWRKy_XdKsb6LNuNH9OlOhbf0T9j5rkqE_qQbDY/edit?usp=sharing).

**Comment by antsandur2** [comment]
Se ha completado también la información de Usuarios pilotos y subido el último feedback.

Se ha documentado la aportación en el archivo de Drive [Base del conocimiento](https://docs.google.com/document/d/17m1uCWRKy_XdKsb6LNuNH9OlOhbf0T9j5rkqE_qQbDY/edit?usp=sharing) y en el archivo [Informe-10](https://docs.google.com/document/d/1FoNrovLX1sxla_7utNTmuCz2FdfvgvyoQd9av8a48I8/edit?usp=sharing)
